server:
  port: 8085
spring:
  application:
    name: "OpenBox"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: #urlDataBaseMongo
  rabbitmq:
    host: #hostname
    port: 5671
    username: #username
    password: #password
    virtual-host: #hostname
    ssl:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
